@startuml
skinparam ParticipantPadding 70
skinparam BoxPadding 10

skinparam backgroundColor #EEEBDC


skinparam sequence {
	ArrowColor Blue
	ActorBorderColor Blue
	LifeLineBorderColor blue
	LifeLineBackgroundColor #DeepSkyBlue

	ParticipantBorderColor Blue
	ParticipantBackgroundColor LightBlue
	ParticipantFontName Impact
	ParticipantFontSize 17
	ParticipantFontColor Orangered

	ActorBackgroundColor lightgreen
	ActorFontColor orangered
	ActorFontSize 17
	ActorFontName Aapex
}

actor "User" as A
participant "WebPage" as B
participant "Server" as C

A ->> B: Enters coordinates of figure
activate B
B ->> C: Sends coordinates of figure
activate C
C ->> C: Process incoming data
C ->> B: Returns info about inputed figure
deactivate C
B ->> A: Shows result
deactivate B

@enduml