@startuml

skinparam backgroundColor mediumpurple
skinparam activity {
  StartColor orangered
  BarColor SaddleBrown
  EndColor orangered
  BackgroundColor Peru
  BackgroundColor<< Begin >> Olive
  BorderColor Peru
  FontName Impact
}

start
repeat
#skyblue :Choose figure;
if (Triangle is chosen?) then (yes)
#lightgreen :Enter 3 Points of Triangle;
#lightgreen :Push button "Calculate Triangle";
#lightgreen :Check Perimetr, Square and type of Triangle;
#lightgreen :Check how Triangle looks like;
elseif (Quadrilateral is chosen?) then (yes)
#lightgreen :Enter 4 Points of Quadrilateral;
#lightgreen :Push button "Calculate Quadrilateral";
#lightgreen :Check Perimetr, Square and type of Quadrilateral;
#lightgreen :Check how Quadrilateral looks like;
elseif (Pentagon is chosen?) then (yes)
#lightgreen :Enter 5 Points of Pentagon;
#lightgreen :Push button "calculate pentagon";
#lightgreen :Check Perimetr, Square and type of Pentagon;
#lightgreen :Check how Pentagon looks like;
endif
repeat while (Draw more figures?)
stop

@enduml