@startuml

skinparam class {
	BackgroundColor DarkKhaki
	ArrowColor SeaGreen
	BorderColor Green
}
skinparam stereotypeCBackgroundColor LightSeaGreen



class Point {
-Double x
-Double y

+get_x()
+set_x()
+get_y()
+set_y()
}

class Distance{
-Point{} a
-Point{} b

+length() : Double
+length_2() : Double
+notSimiliar() : Boolean
}

class Figure
{
   -String type
   -Int number_of_angles

   +get_type()
   +get_angles()
   +showType()
   +showAngles()
}

class Triangle{
-Distance{} d1
-Distance{} d2
-Distance{} d3

+isTriangle() : Boolean
+perimetr() : Double
+square() : Double
+isRect() : Boolean
+isEqual() : Boolean
+isIsos() : Boolean
}

class Quad{
-Distance{} d1
-Distance{} d2
-Distance{} d3
-Distance{} d4
-Distance{} d1_d2

+perimetr() : Double
+square() : Double
+s_of_sq() : Double
+s_of_rect() : Double
+isSquare() : Boolean
+isRhombus() : Boolean
+isRectangle() : Boolean
+isisParallelogram() : Boolean
}

class Pentagon{
-Distance{} d1
-Distance{} d2
-Distance{} d3
-Distance{} d4
-Distance{} d5

+perimetr() : Double
+sq() : Double
+sq_Rt() : Double
+isRightPent() : Boolean
}

Point --* Distance
Distance --* Figure
Figure --* Triangle
Figure --* Quad
Figure --* Pentagon

@enduml